### ISSUE TITLE
eventually: v0.4.0 tracking release

### ISSUE THREAD

**Issue by ar3s3ru** [ar3s3ru/eventually-rs#54]
For v0.4.0, the plan is pretty big, and I'd mainly focus it around API design and missing features to make it viable for small, but powerful-enough solutions.

- [x] `AggregateId` is owned by and exposed through the `AggregateRoot` (#53)
- [x] Versioning is embedded in the `AggregateRoot`, remove `eventually::versioned` (#56)
- [x] Fix versioning by delegating version increments to the `EventStore` (#62)
- [x] Add `EventStore::stream_all` support (#81)
- [x] Overhaul of `eventually-postgres` crate (#86)
- [x] Add `Subscriber` support, to listen to new changes to the `EventStore` (#88)
- [x] Add `Subscriber` implementation for Postgres (#92)
- [x] Projections support (#93)
- [x] Add support for `PersistentSubscription` (#101)
- [x] Write introductory documentation to explain the components and architecture (#46)

**Note:** since the plan is not finalized yet, this list is subject to changes.
