### ISSUE TITLE
eventually-postgres: Overhaul after v0.4.0 breaking changes

### ISSUE THREAD

**Issue by ar3s3ru** [ar3s3ru/eventually-rs#86]
The current state of `eventually-postgres` is pretty bad, being disabled after #81 has been merged.

Things that are currently missing in the crate:
- [x] Proper schema for aggregates/events (#87)
- [x] Schema migration tool to run at startup (use https://github.com/rust-db/refinery) (#87)
- [x] Move sequence numbering and versioning to the database (using triggers or functions?) (#87)
- [ ] Use `NOTIFY/LISTEN` for creating persistent streams

## Schema for Aggregates and Events

The database should potentially support a multi-Aggregate setup, so the proposed tables layout looks like this:

### Aggregate Types

Contains all the Aggregate types definition in a centralized place.

| *Column Name* | *Description*                                                                                                    |
|---------------|------------------------------------------------------------------------------------------------------------------|
| `id`        | Type identifier of the Aggregate -- might use [`type_name`](https://doc.rust-lang.org/std/any/fn.type_name.html) |
| `offset`      | Global offset of the `$all` stream.                                                                              |

### Aggregates

Contains all the Aggregates created by the application.

| *Column Name*       | *Description*                                                                             |
|---------------------|-------------------------------------------------------------------------------------------|
| `id`                | Aggregate ID -- should be **unique** and a **string**.                                    |
| `aggregate_type_id` | Reference to the `aggregate_types` table. Useful for accessing the Aggregate Type offset. |
| `version`           | Last version of the Aggregate.                                                            |

### Events

| *Column Name*     | *Description*                                                                                         |
|-------------------|-------------------------------------------------------------------------------------------------------|
| `aggregate_id`    | Reference to the `aggregates` table.                                                                  |
| `version`         | Version of the Event, for Optimistic Concurrency.                                                     |
| `sequence_number` | Value of the Global Offset at the time of insert -- useful for `$all` streams publishing idempotency. |
| `event`           | Contents of the event -- should be a **JSON**.                                                        |

#### Notes

* `(aggregate_id, version)` should be unique.

**Comment by ar3s3ru** [comment]
>Use `NOTIFY/LISTEN` for creating persistent streams

This will be done as part of the Subscription implementation. More info to come.
